name: server
description: A server app using the shelf package and Docker.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0

environment:
  sdk: ^3.1.5

dependencies:
  common:
    path: ../common
  args: ^2.4.2
  collection: ^1.18.0
  json_annotation: ^4.8.1
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2
  stack_trace: ^1.11.1

dev_dependencies:
  build_runner: any
  lints: ^3.0.0
  json_serializable: ^6.7.1
  http: ^1.1.0
  test: ^1.25.2
