targets:
  $default:
    builders:
      json_serializable:
        options:
          any_map: false
          checked: false
          explicit_to_json: true
          include_if_null: false
          field_rename: snake
