name: common
description: Common code shared between app and server modules
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0'

dependencies:
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: any
  lints: ^3.0.0
  json_serializable: ^6.7.1
